@echo off
cd /d "%~dp0"
echo === NeoMUDMaker ===
echo Installing dependencies...
call npm install
echo Generating Prisma client...
call npx prisma generate
echo Killing stale Vite dev server (if any)...
call npx tsx scripts/kill-port.ts
echo Starting dev server...
call npm run dev
pause
